# Generated by Django 3.0.8 on 2020-07-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20200705_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city_type',
            new_name='address_type',
        ),
    ]
