# Generated by Django 3.0.8 on 2020-07-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_auto_20200705_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('W', 'WORK'), ('H', 'HOME')], max_length=2),
        ),
    ]
