# Generated by Django 3.0.8 on 2020-07-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('W', 'WORK'), ('H', 'HOME')], max_length=2),
        ),
        migrations.RenameModel(
            old_name='Brand',
            new_name='BrandName',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Type',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ca_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CategoriesName')),
                ('typeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.BrandName')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CategoriesName')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CategoriesName'),
        ),
    ]
