# Generated by Django 3.0.8 on 2020-07-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200711_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
