# Generated by Django 3.0.8 on 2020-07-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_type_type_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandname',
            name='brand_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('W', 'WORK'), ('H', 'HOME')], max_length=2),
        ),
    ]
