# Generated by Django 3.0.8 on 2020-07-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200712_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('W', 'WORK'), ('H', 'HOME')], max_length=2),
        ),
    ]
