# Generated by Django 3.0.8 on 2020-07-16 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_products_image_high'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Type'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('H', 'HOME'), ('W', 'WORK')], max_length=2),
        ),
    ]
