# Generated by Django 3.0.8 on 2020-07-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesname',
            name='cat_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
