# Generated by Django 3.0.8 on 2020-07-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_categoriesname_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('W', 'WORK'), ('H', 'HOME')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='categoriesname',
            name='type',
        ),
        migrations.AddField(
            model_name='categoriesname',
            name='type',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='shop.Type'),
        ),
    ]
